# Generated by Django 5.1.7 on 2025-03-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_quantity_alter_order_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
    ]
